### ISSUE TITLE
Test convert issue to epic

### ISSUE THREAD

**Issue by aheimsbakk** [metno/S-ENDA-Prototype#28]
What will happen when I convert this issue to an Epic?

**Comment by mpejcoch** [comment]
@aheimsbakk Was that just the label change?

**Comment by mortenwh** [comment]
@aheimsbakk @mpejcoch - the change was done in zenhub. I didn't see the label before now. But this is quite good, because it means that we can define epics directly in github!

Regarding epics - I'm considering to add the "oppgaver" from the project description as epics. Does that make sense? Each epic will then have deliveries as defined in the project description, plus other issues that come up...

**Comment by mortenwh** [comment]
I checked if I could make an epic directly in github by adding the Epic label. Unfortunately, it doesn't seem to work, so we'll need to define the epics in zenhub.
